### ISSUE TITLE
No releases yet?

### ISSUE THREAD

**Issue by sassy-crick** [loosolab/TF-COMB#46]
Dear all,

I have been asked to install the code on our HPC cluster. Whereas that is fine with me, I noticed the distinct lack of a release. 
Whereas I can use the Git-Tags as a 'release', it would be good to have a proper release, like for example the way it is suggested here:
http://semver.org/

Would that be possible?

Thanks!

**Comment by msbentsen** [comment]
Hi @sassy-crick,

Yes of course, that is certainly possible! This was always the plan, I guess we have just been a little slow at making the actual release. I have just uploaded this project to PyPI (https://pypi.org/project/TF-COMB/) and also made a release of version `1.0.0` here on github.

Thank you for making us aware and I hope this makes installing a bit more comfortable!

**Comment by sassy-crick** [comment]
Hi @msbentsen 

Many thanks for the prompt reply, which is much appreciated!
That makes my life easier and hopefully yours too, as it means I will open a PR with EasyBuild and hopefully we can get your software in there.
This will make it more comfortable for the community to install it. 

Thanks!

**Comment by msbentsen** [comment]
Sounds great with EasyBuild - I hope your organization and others will get value of this tool!

I will close this, but do let me know in case of any issues with install or usage :-)
