### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute '_version_'

### ISSUE THREAD

**Issue by hcph** [loosolab/TF-COMB#47]
Hello, when I import the tfcomb in python 3.8.6, I got this error:

from mpl_toolkits.axes_grid.inset_locator import inset_axes
ModuleNotFoundError: No module named 'mpl_toolkits.axes_grid'

Could you please help me to fix it? besh wished and thanks.

**Comment by msbentsen** [comment]
Hi @hcph ,

Thank you for this issue! Turns out this function was deprecated recently in matplotlib 3.6.0, which we did not take into account - but this is now fixed in `TF-COMB 1.0.1`! Can you try to install the new version from PyPI again?

**Comment by hcph** [comment]
Thank you for your quickly and useful reply.  I will try your suggestions. -------- 原始邮件 --------发件人： Mette Bentsen ***@***.***>日期： 2022年11月24日周四 傍晚6:36收件人： loosolab/TF-COMB ***@***.***>抄送： HC ***@***.***>, Mention ***@***.***>主    题： Re: [loosolab/TF-COMB] AttributeError: module 'matplotlib' has no attribute '_version_' (Issue #47)
Hi @hcph ,
Thank you for this issue! Turns out this function was deprecated recently in matplotlib 3.6.0, which we did not take into account - but this is now fixed in TF-COMB 1.0.1! Can you try to install the new version from PyPI again?

**Comment by hcph** [comment]
Hi @msbentsen，after I install the new version of TF-COMB 1.0.1, the error was gone. Thank you again!
