### ISSUE TITLE
InputError: Region is out of bounds in the given genome

### ISSUE THREAD

**Issue by GudaLab** [loosolab/TF-COMB#49]
I am performing the Search for TFBS within peak regions (As shown here https://tf-comb.readthedocs.io/en/latest/examples/TFBS_from_motifs.html#Search-for-TFBS-within-peak-regions) under TFBS from motifs  after the Setup a CombObj. I used hg38, hg19 and even hs1 reference sequence. I am encountering the error as shown below. Any idea how I can resolve this?

```
C.TFBS_from_motifs(regions="/Users/arch/Desktop/neuroncontrol440controlvsneuronheroin484treatment.mRp.clN.deseq2.FDR0.05.results.bed",
                   motifs="/Users/arch/Desktop/JASPAR2022_CORE_vertebrates_non-redundant_pfms_meme.txt",
                   genome="/Users/arch/Desktop/genome.fa",
                   threads=8)
```

InputError: Region 'chr1 249119901 249121078 Interval_38857' is out of bounds in the given genome. The length of the chromosome is: 248956422

**Comment by hschult** [comment]
Hi,
the error suggests that you have ranges in your bed that are outside the genomes coordinates. If you remove those everything should work :)

**Comment by hschult** [comment]
I'm closing this for now. Feel free to reopen if the issue persists.
