### ISSUE TITLE
Plot footprints

### ISSUE THREAD

**Issue by Rajashree93** [loosolab/TF-COMB#66]
>>> **pairs.pairMap(pairs.pairMap(logNorm_cbar=None, show_binding=True, flank_plot="strand", figsize=(6, 6), output="Image.pdf", flank=(50, 150), align="left", alpha=0.3, cmap="seismic", show_diagonal=True, legend_name_score="Bigwig Score", xtick_num=10, log=np.log1p, dpi=100))**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/util/opt/anaconda/deployed-conda-envs/packages/tf-comb/envs/tf-comb-1.0.3-py310/lib/python3.10/site-packages/tfcomb/utils.py", line 493, in pairMap
    raise ValueError(f"Parameter 'logNorm_cbar' has to be one of [None, \"centerLogNorm\", \"SymLogNorm\"]. But found {logNorm_cbar}.")
ValueError: Parameter 'logNorm_cbar' has to be one of [None, "centerLogNorm", "SymLogNorm"]. But found GridSpec(1, 2, width_ratios=[1, 10]).

I run TF_COMB on terminal on server as it gives errors when ran on anything else oin my computer. Can you please tell me:

1. Why it is giving error for 'logNorm_cbar' when I am putting none?
2. How to save the image generated on terminal? I have tried to save with the **'output=path'** command and with **'save=path'** command, didnt work. Can you please let me know what else can I do?

**Comment by vheger** [comment]
Hi @Rajashree93, 

I noticed you called the function twice, which causes the error. 
Could you please try the following command, which should resolve the Issue. 
```
pairs.pairMap(logNorm_cbar=None, show_binding=True, flank_plot="strand", figsize=(6, 6), output="Image.pdf", flank=(50, 150), align="left", alpha=0.3, cmap="seismic", show_diagonal=True, legend_name_score="Bigwig Score", xtick_num=10, log=np.log1p, dpi=100)
```

For your second question: `output=path` is the right way to do it in this case. Please remember to substitute or assign `path` with the actual path on your server, e.g. `/path/to/the/file/filename.pdf`

If this doesn't work for you please let me know and I'm happy to assist you further. 

Kind regards
Vanessa
