### ISSUE TITLE
`TFBSpairList.pairMap` function chromosome naming issue

### ISSUE THREAD

**Issue by Myrtle-bio** [loosolab/TF-COMB#75]
Hi! 

When I was using this function, I encoutered a error "RuntimeError: You must supply a chromosome, start and end position."

I spent some time on this error. I discovered the problem was related to the naming of chromosomes in some plants, which are numerically labeled as 1, 2, 3, 4, 5, 6, etc. The issue arose when using the function 

`signal_bigwig.values(row["site1_chrom"], row["window_start"], row["window_end"]).`

The function did not account for converting row["site1_chrom"] to a string, leading to errors. 

I want to bring this issue to attention to save future users time in resolving similar problems. 

A possible solution is to modify the code in util.py at lines 386 and 408. Changing signal_bigwig.values(row["site1_chrom"], row["window_end"], row["window_start"]) to signal_bigwig.values(str(row["site1_chrom"]), row["window_end"], row["window_start"]) can rectify this issue.

**Comment by hschult** [comment]
Hi @Myrtle-bio,

thank you for reporting this bug. I have created a fix and added it to our development version. You can install it with `pip install git+git://github.com/loosolab/TF-COMB@dev`. It will be included in our upcoming TF-Comb release.

Feel free to reopen should the error persist.
Best,
Hendrik
